<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MixPlus.Modules.Cart</RootNamespace>
    <AssemblyName>MixPlus.Modules.Cart</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\MixPlus.BuildingBlocks\MixPlus.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
