<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>MixPlus.Modules.Search</RootNamespace>
    <AssemblyName>MixPlus.Modules.Search</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\MixPlus.BuildingBlocks\MixPlus.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
